spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      sqs:
        enabled: true
        endpoint: http://localhost:4566
      region:
        static: ap-northeast-2
      s3:
        endpoint: http://localhost:4566
        path-style-access-enabled: true
      credentials:
        access-key: test-access-key
        secret-key: test-secret-key

app:
  seat:
    hold-ttl-seconds: 10
